config:
  project: 中台搜索Springboot demo~~~~
  environment: test
  environmentURL: https://vms-t13.tezign.com

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: Springboot demo
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://10.80.82.13:3306/t13?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username:  vms_developer
    password: WDSFREWFD2@VDVdc2d
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10
    min-idle: 5



#logging:
#  config: classpath:logback.xml
#

##  server.port=8080
##
##  #数据库相关配置
##  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##  spring.datasource.url=jdbc:mysql://localhost:3306/hogwarts
##  spring.datasource.username=root
##  spring.datasource.password=mysql0512
##  spring.datasource.max-idle=10
##  spring.datasource.max-wait=10000
##  spring.datasource.min-idle=5